name: Lint Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ESLint
        run: |
          npm install eslint
          npx eslint .
      - name: Notify Success
        run: echo "Linting complete! All checks passed."
